import 'package:equatable/equatable.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

part 'quran_event.dart';
part 'quran_state.dart';

class QuranBloc extends Bloc<QuranEvent, QuranState> {
  QuranBloc() : super(const QuranState()) {
    on<GetQuranBooksEvent>(_onGetQuranBooks);
    on<SelectQuranBookEvent>(_onSelectQuranBook);
    on<PlayQuranSurahEvent>(_onPlayQuranSurah);
    on<StopQuranPlaybackEvent>(_onStopQuranPlayback);
  }

  // Карта Сур с их аудио путями (все 114 Сур Корана)
  final Map<int, String> surahAudioPaths = {
    1: 'assets/audio/quran/001_al_fatihah.mp3',
    2: 'assets/audio/quran/002_al_baqarah.mp3',
    3: 'assets/audio/quran/003_al_imran.mp3',
    4: 'assets/audio/quran/004_an_nisa.mp3',
    5: 'assets/audio/quran/005_al_maidah.mp3',
    6: 'assets/audio/quran/006_al_anam.mp3',
    7: 'assets/audio/quran/007_al_araf.mp3',
    8: 'assets/audio/quran/008_al_anfal.mp3',
    9: 'assets/audio/quran/009_at_tawbah.mp3',
    10: 'assets/audio/quran/010_yunus.mp3',
    11: 'assets/audio/quran/011_hud.mp3',
    12: 'assets/audio/quran/012_yusuf.mp3',
    13: 'assets/audio/quran/013_ar_rad.mp3',
    14: 'assets/audio/quran/014_ibrahim.mp3',
    15: 'assets/audio/quran/015_al_hijr.mp3',
    16: 'assets/audio/quran/016_an_nahl.mp3',
    17: 'assets/audio/quran/017_al_isra.mp3',
    18: 'assets/audio/quran/018_al_kahf.mp3',
    19: 'assets/audio/quran/019_maryam.mp3',
    20: 'assets/audio/quran/020_ta_ha.mp3',
    21: 'assets/audio/quran/021_al_anbiya.mp3',
    22: 'assets/audio/quran/022_al_hajj.mp3',
    23: 'assets/audio/quran/023_al_muminum.mp3',
    24: 'assets/audio/quran/024_an_nur.mp3',
    25: 'assets/audio/quran/025_al_furqan.mp3',
    26: 'assets/audio/quran/026_ash_shuara.mp3',
    27: 'assets/audio/quran/027_an_naml.mp3',
    28: 'assets/audio/quran/028_al_qasas.mp3',
    29: 'assets/audio/quran/029_al_ankabut.mp3',
    30: 'assets/audio/quran/030_ar_rum.mp3',
    31: 'assets/audio/quran/031_luqman.mp3',
    32: 'assets/audio/quran/032_as_sajdah.mp3',
    33: 'assets/audio/quran/033_al_ahzab.mp3',
    34: 'assets/audio/quran/034_saba.mp3',
    35: 'assets/audio/quran/035_fatir.mp3',
    36: 'assets/audio/quran/036_ya_sin.mp3',
    37: 'assets/audio/quran/037_as_saffat.mp3',
    38: 'assets/audio/quran/038_sad.mp3',
    39: 'assets/audio/quran/039_az_zumar.mp3',
    40: 'assets/audio/quran/040_ghafir.mp3',
    41: 'assets/audio/quran/041_fussilat.mp3',
    42: 'assets/audio/quran/042_ash_shura.mp3',
    43: 'assets/audio/quran/043_az_zukhruf.mp3',
    44: 'assets/audio/quran/044_ad_dukhan.mp3',
    45: 'assets/audio/quran/045_al_jathiya.mp3',
    46: 'assets/audio/quran/046_al_ahqaf.mp3',
    47: 'assets/audio/quran/047_muhammad.mp3',
    48: 'assets/audio/quran/048_al_fath.mp3',
    49: 'assets/audio/quran/049_al_hujurat.mp3',
    50: 'assets/audio/quran/050_qaf.mp3',
    51: 'assets/audio/quran/051_adh_dhariyat.mp3',
    52: 'assets/audio/quran/052_at_tur.mp3',
    53: 'assets/audio/quran/053_an_najm.mp3',
    54: 'assets/audio/quran/054_al_qamar.mp3',
    55: 'assets/audio/quran/055_ar_rahman.mp3',
    56: 'assets/audio/quran/056_al_waqiah.mp3',
    57: 'assets/audio/quran/057_al_hadid.mp3',
    58: 'assets/audio/quran/058_al_mujadalah.mp3',
    59: 'assets/audio/quran/059_al_hashr.mp3',
    60: 'assets/audio/quran/060_al_mumtahanah.mp3',
    61: 'assets/audio/quran/061_as_saff.mp3',
    62: 'assets/audio/quran/062_al_jumuah.mp3',
    63: 'assets/audio/quran/063_al_munafiqun.mp3',
    64: 'assets/audio/quran/064_at_taghabun.mp3',
    65: 'assets/audio/quran/065_at_talaq.mp3',
    66: 'assets/audio/quran/066_at_tahrim.mp3',
    67: 'assets/audio/quran/067_al_mulk.mp3',
    68: 'assets/audio/quran/068_al_qalam.mp3',
    69: 'assets/audio/quran/069_al_haqqah.mp3',
    70: 'assets/audio/quran/070_al_maarij.mp3',
    71: 'assets/audio/quran/071_nuh.mp3',
    72: 'assets/audio/quran/072_al_jinn.mp3',
    73: 'assets/audio/quran/073_al_muzzammil.mp3',
    74: 'assets/audio/quran/074_al_muddaththir.mp3',
    75: 'assets/audio/quran/075_al_qiyamah.mp3',
    76: 'assets/audio/quran/076_al_insan.mp3',
    77: 'assets/audio/quran/077_al_mursalat.mp3',
    78: 'assets/audio/quran/078_an_naba.mp3',
    79: 'assets/audio/quran/079_an_naziat.mp3',
    80: 'assets/audio/quran/080_abasa.mp3',
    81: 'assets/audio/quran/081_at_takwir.mp3',
    82: 'assets/audio/quran/082_al_infitar.mp3',
    83: 'assets/audio/quran/083_al_mutaffifin.mp3',
    84: 'assets/audio/quran/084_al_inshiqaq.mp3',
    85: 'assets/audio/quran/085_al_buruj.mp3',
    86: 'assets/audio/quran/086_at_tariq.mp3',
    87: 'assets/audio/quran/087_al_ala.mp3',
    88: 'assets/audio/quran/088_al_ghashiyah.mp3',
    89: 'assets/audio/quran/089_al_fajr.mp3',
    90: 'assets/audio/quran/090_al_balad.mp3',
    91: 'assets/audio/quran/091_ash_shams.mp3',
    92: 'assets/audio/quran/092_al_lail.mp3',
    93: 'assets/audio/quran/093_ad_duha.mp3',
    94: 'assets/audio/quran/094_ash_sharh.mp3',
    95: 'assets/audio/quran/095_at_tin.mp3',
    96: 'assets/audio/quran/096_al_alaq.mp3',
    97: 'assets/audio/quran/097_al_qadr.mp3',
    98: 'assets/audio/quran/098_al_bayyinah.mp3',
    99: 'assets/audio/quran/099_az_zalzalah.mp3',
    100: 'assets/audio/quran/100_al_adiyat.mp3',
    101: 'assets/audio/quran/101_al_qaria.mp3',
    102: 'assets/audio/quran/102_at_takathur.mp3',
    103: 'assets/audio/quran/103_al_asr.mp3',
    104: 'assets/audio/quran/104_al_humaza.mp3',
    105: 'assets/audio/quran/105_al_fil.mp3',
    106: 'assets/audio/quran/106_quraysh.mp3',
    107: 'assets/audio/quran/107_al_maun.mp3',
    108: 'assets/audio/quran/108_al_kawthar.mp3',
    109: 'assets/audio/quran/109_al_kafirun.mp3',
    110: 'assets/audio/quran/110_an_nasr.mp3',
    111: 'assets/audio/quran/111_al_lahab.mp3',
    112: 'assets/audio/quran/112_al_ikhlas.mp3',
    113: 'assets/audio/quran/113_al_falaq.mp3',
    114: 'assets/audio/quran/114_an_nas.mp3',
  };

  Future<void> _onGetQuranBooks(
      GetQuranBooksEvent event, Emitter<QuranState> emit) async {
    emit(state.copyWith(quranStatus: Status.loading));
    
    try {
      // All 114 Surahs of the Holy Quran
      final quranBooks = [
        'Al-Fatihah (The Opening)',
        'Al-Baqarah (The Cow)',
        'Al-Imran (The Family of Imran)',
        'An-Nisa (The Women)',
        'Al-Maidah (The Table Spread)',
        'Al-Anam (The Cattle)',
        'Al-Araf (The Heights)',
        'Al-Anfal (The Spoils of War)',
        'At-Tawbah (The Repentance)',
        'Yunus (Jonah)',
        'Hud (Hud)',
        'Yusuf (Joseph)',
        'Ar-Rad (The Thunder)',
        'Ibrahim (Abraham)',
        'Al-Hijr (The Rocky Tract)',
        'An-Nahl (The Bee)',
        'Al-Isra (The Night Journey)',
        'Al-Kahf (The Cave)',
        'Maryam (Mary)',
        'Ta-Ha (Ta-Ha)',
        'Al-Anbiya (The Prophets)',
        'Al-Hajj (The Pilgrimage)',
        'Al-Muminum (The Believers)',
        'An-Nur (The Light)',
        'Al-Furqan (The Criterion)',
        'Ash-Shuara (The Poets)',
        'An-Naml (The Ant)',
        'Al-Qasas (The Stories)',
        'Al-Ankabut (The Spider)',
        'Ar-Rum (The Roman)',
        'Luqman (Luqman)',
        'As-Sajdah (The Prostration)',
        'Al-Ahzab (The Confederates)',
        'Saba (Sheba)',
        'Fatir (Originator)',
        'Ya-Sin (Ya-Sin)',
        'As-Saffat (Those Who Set the Ranks)',
        'Sad (Sad)',
        'Az-Zumar (The Groups)',
        'Ghafir (The Forgiver)',
        'Fussilat (Explained in Detail)',
        'Ash-Shura (Consultation)',
        'Az-Zukhruf (The Ornament)',
        'Ad-Dukhan (The Smoke)',
        'Al-Jathiya (The Crouching)',
        'Al-Ahqaf (The Winds)',
        'Muhammad (Muhammad)',
        'Al-Fath (The Victory)',
        'Al-Hujurat (The Rooms)',
        'Qaf (Qaf)',
        'Adh-Dhariyat (The Scatterers)',
        'At-Tur (The Mount)',
        'An-Najm (The Star)',
        'Al-Qamar (The Moon)',
        'Ar-Rahman (The Most Merciful)',
        'Al-Waqiah (The Inevitable)',
        'Al-Hadid (The Iron)',
        'Al-Mujadalah (The Pleading Woman)',
        'Al-Hashr (The Exile)',
        'Al-Mumtahanah (She That Is to Be Examined)',
        'As-Saff (The Ranks)',
        'Al-Jumuah (The Friday)',
        'Al-Munafiqun (The Hypocrites)',
        'At-Taghabun (The Mutual Loss)',
        'At-Talaq (The Divorce)',
        'At-Tahrim (The Prohibition)',
        'Al-Mulk (The Kingdom)',
        'Al-Qalam (The Pen)',
        'Al-Haqqah (The Inevitable Reality)',
        'Al-Maarij (The Ascending Stairways)',
        'Nuh (Noah)',
        'Al-Jinn (The Jinn)',
        'Al-Muzzammil (The Enveloped One)',
        'Al-Muddaththir (The Cloaked One)',
        'Al-Qiyamah (The Resurrection)',
        'Al-Insan (The Human)',
        'Al-Mursalat (Those Sent Forth)',
        'An-Naba (The Announcement)',
        'An-Naziat (Those Who Tear Out)',
        'Abasa (He Frowned)',
        'At-Takwir (The Overthrowing)',
        'Al-Infitar (The Splitting)',
        'Al-Mutaffifin (Those Who Deal in Fraud)',
        'Al-Inshiqaq (The Splitting Asunder)',
        'Al-Buruj (The Constellations)',
        'At-Tariq (The Nightcomer)',
        'Al-Ala (The Most High)',
        'Al-Ghashiyah (The Overwhelming)',
        'Al-Fajr (The Dawn)',
        'Al-Balad (The City)',
        'Ash-Shams (The Sun)',
        'Al-Lail (The Night)',
        'Ad-Duha (The Forenoon)',
        'Ash-Sharh (The Opening)',
        'At-Tin (The Fig)',
        'Al-Alaq (The Clot)',
        'Al-Qadr (The Power)',
        'Al-Bayyinah (The Clear Proof)',
        'Az-Zalzalah (The Earthquake)',
        'Al-Adiyat (The Charging Steeds)',
        'Al-Qaria (The Striking Hour)',
        'At-Takathur (The Rivalry)',
        'Al-Asr (The Declining Day)',
        'Al-Humaza (The Slanderer)',
        'Al-Fil (The Elephant)',
        'Quraysh (Quraysh)',
        'Al-Maun (The Small Kindness)',
        'Al-Kawthar (The Abundance)',
        'Al-Kafirun (The Disbelievers)',
        'An-Nasr (The Victory)',
        'Al-Lahab (The Flame)',
        'Al-Ikhlas (The Oneness)',
        'Al-Falaq (The Dawn)',
        'An-Nas (Mankind)',
      ];

      emit(state.copyWith(
        quranBooks: quranBooks,
        quranStatus: Status.complete,
      ));
    } catch (e) {
      emit(state.copyWith(quranStatus: Status.error));
    }
  }

  Future<void> _onSelectQuranBook(
      SelectQuranBookEvent event, Emitter<QuranState> emit) async {
    emit(state.copyWith(
      selectedBook: event.bookName,
      selectedSurahNumber: event.surahNumber,
    ));
  }

  Future<void> _onPlayQuranSurah(
      PlayQuranSurahEvent event, Emitter<QuranState> emit) async {
    emit(state.copyWith(
      playingSurahNumber: event.surahNumber,
      playingSurahName: event.surahName,
      isPlaying: true,
    ));
  }

  Future<void> _onStopQuranPlayback(
      StopQuranPlaybackEvent event, Emitter<QuranState> emit) async {
    emit(state.copyWith(
      isPlaying: false,
      playingSurahNumber: null,
      playingSurahName: null,
    ));
  }
}
